# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191206_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
    ]
