# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_column='姓名', max_length=100, verbose_name='用户名'),
        ),
    ]
