# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-07 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191207_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sex', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='boy_num',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='girl_num',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Grade'),
        ),
    ]
