# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-07 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191207_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='boy_num',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='grade',
            name='girl_num',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
