# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191207_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='people',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='blog.People'),
        ),
    ]
