# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-07 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191207_1555'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('my_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='Normal', max_length=100),
        ),
    ]
